[package]
name = "nft-drop"
version = "1.0.0"
license = "MIT"


[dependencies]
AptosFramework = { local = "../../../framework/aptos-framework" }
AptosStdlib = { local = "../../../framework/aptos-stdlib"}
AptosToken = { local = "../../../framework/aptos-token" }

[addresses]
aptos_framework = "0x1"
aptos_std = "0x2"
aptos_token = "0x3"
admin_addr = "_"
