[package]
name = "Pool"
version = "1.0.0"
authors = []

[addresses]
pool="0x6a2713e6fc577763fc77dd88a3900b502e845a84a16e0051f7d097c44ba6daaf"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]