[package]
name = "Pool"
version = "1.0.0"
authors = []

[addresses]
pool="0xa3d1f36631889d1dd502b2db35a5649c7b73ee7edf0a446ea397396b2e038d19"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]