[package]
name = "Pool"
version = "1.0.0"
authors = []

[addresses]
pool="0x81621ab2b6cf09b7195b6ddec510a0829ed0a3e60f77dac2fd4fd1a4e8f8bd5e"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]