[package]
name = "Pool"
version = "1.0.0"
authors = []

[addresses]
pool="0xe973d80bcf97fdf81425983d7fb96771537a28ec67aab14ed4d89900e49cd7ab"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]